### PR TITLE
Bumpup dbt-bigquery 1.8

### LINKED ISSUE #68: Support dbt-core / dbt-bigquery 1.8
dbt-core 1.8 has been released,  so I think need to follow.

### PR DESCRIPTION
**Pull request by w1mvy**
# Description

Fixes #68 

This PR, included #67.

dbt-core 1.8 has been followed due to its impact on functions used in dbt-dry-run. https://github.com/dbt-labs/dbt-adapters/discussions/87

dbt-core 1.8 has just been released, so there may be an idea to wait for the stable version.
I would be happy to point this out to you.

# Checklist:

- [x] I have run `make verify` and fixed any linting or test errors
- [x] I have added appropriate unit tests or if applicable an integration test
- [ ] OPTIONAL: I have run `make integration` against a Big Query instance

### CODE REVIEW

**Comment by ccharlesgb** [comment]
Hey,

Thanks for the pull request! Looks like all the integration tests are failing (They don't run on the PR GH action) on this branch due to:

```
.venv/lib/python3.8/site-packages/jinja2/sandbox.py:394: in call
    return __context.call(__obj, *args, **kwargs)
.venv/lib/python3.8/site-packages/dbt/context/secret.py:32: in env_var
    env = get_invocation_context().env
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def get_invocation_context() -> InvocationContext:
        invocation_var = reliably_get_invocation_var()
>       ctx = invocation_var.get()
E       LookupError: <ContextVar name='DBT_INVOCATION_CONTEXT_VAR' at 0x1645f02c0>

.venv/lib/python3.8/site-packages/dbt_common/context.py:53: LookupError
________________________________________________________________________________ ERROR at setup of test_tests_for_missing_models_are_not_executed _________________________________________________________________________________

request = <SubRequest 'compiled_project' for <Function test_valid_tests_are_run>>

    @pytest.fixture(scope="module")
    def compiled_project(request: FixtureRequest) -> ProjectContext:
>       return _compiled_project(request, full_refresh=False)

integration/conftest.py:139: 
```

Do you have a way of setting up running the [integration tests locally](https://github.com/autotraderuk/dbt-dry-run/blob/main/CONTRIBUTING.md#running-integration-tests) on a project you control? If not I can take a look at figuring out what is going on.

**Comment by w1mvy** [comment]
Thanks your review!! (also about #67 

> Do you have a way of setting up running the [integration tests locally](https://github.com/autotraderuk/dbt-dry-run/blob/main/CONTRIBUTING.md#running-integration-tests) on a project you control?

yes. I was able to reference docs and reproduce it.
 But, the investigation is proving difficult.

**Comment by ccharlesgb** [comment]
I can take a look this week if its proving difficult. The integration test setup is a bit fiddly.

**Comment by ccharlesgb** [comment]
Replacing with #71

**Comment by w1mvy** [comment]
I did not take the time to investigate.
Thanks your fix !!

**Pull request closed without merging**
